allowBuilds:
  '@parcel/watcher': true
  cwebp-bin: true
  gifsicle: true
  mozjpeg: true
  optipng-bin: true
  puppeteer: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - cwebp-bin
  - gifsicle
  - mozjpeg
  - optipng-bin
  - puppeteer
